baseURL = "https://gohugo.io/"
author = "Steve Francia"
paginate = 20
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# Above are configs from hugoBasicExample

title = "code.openark.org"
theme = "hugo-primer"
hasCJKLanguage = true
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = ""
disqusShortname=""
copyright = "&copy; Shlomi Noach"

[params]
description = "Blog by Shlomi Noach"
twitter = "ShlomiNoach"
useIcon = false
useTwitterCard = true
# exampleSite must not have js share widget: #36
shareTo = ["Twitter"]
#shareTo = []
showFooterCredits = true
math = true

  [taxonomies]
  category = "category"
  tag = "tag"

[social]
# Link your social networking accouns to the side menu
# by entering your username or ID.
twitter = "ShlomiNoach"
github = "shlomi-noach"
stackoverflow = "" # "1505860/shlomi-noach"
linkedin = "shlominoach"
