baseURL = "https://gohugo.io/"
author = "Steve Francia"
paginate = 20
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# Above are configs from hugoBasicExample

title = "code.openark.org"
theme = "hugo-primer"
hasCJKLanguage = true
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = ""
disqusShortname=""
copyright = "&copy; Shlomi Noach"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/page/about"

  [[menu.main]]
    identifier = "presentations"
    name = "presentations"
    url = "/page/presentations"

  [[menu.main]]
    identifier = "rss"
    name = "rss"
    url = "/post/index.xml"

[params]
description = "Blog by Shlomi Noach"
twitter = "ShlomiNoach"
useIcon = false
useTwitterCard = true
shareTo = ["Twitter"]
showFooterCredits = true
math = true
maxTags = 20

  [taxonomies]
  category = "category"
  tag = "tag"

[social]
# Link your social networking accouns to the side menu
# by entering your username or ID.
name = "Shlomi Noach"
gravatar = "168ccec72eee0530b818d44f3fedaacf"
twitter = "ShlomiNoach"
github = "shlomi-noach"
stackoverflow = "" # "1505860/shlomi-noach"
linkedin = "shlominoach"
