---
archetypedir:               "archetype"
# hostname (and path) to the root, e.g. http://spf13.com/
baseURL:                    "/blog"
# include content marked as draft
buildDrafts:                false
# include content with publishdate in the future
buildFuture:                false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs:               false
canonifyURLs:               false
# config file (default is path/config.yaml|json|toml)
config:                     "config.toml"
contentdir:                 "content"
dataDir:                    "data"
defaultExtension:           "html"
defaultLayout:              "post"
disableLiveReload:          false
# Do not build RSS files
disableRSS:                 false
# Do not build Sitemap file
disableSitemap:             false
# Build robots.txt file
enableRobotsTXT:            false
# Do not render 404 page
disable404:                 false
# Do not inject generator meta tag on homepage
disableHugoGeneratorInject: false
# edit new content with this editor, if provided
editor:                     ""
# Enable Emoji emoticons support for page content.
# See www.emoji-cheat-sheet.com
enableEmoji:                false
footnoteAnchorPrefix:       ""
footnoteReturnLinkContents: ""
# google analytics tracking id
googleAnalytics:            ""
languageCode:               "en-us"
layoutdir:                  "layouts"
# Enable Logging
log:                        false
# Log File path (if set, logging enabled automatically)
logFile:                    ""
# "yaml", "toml", "json"
metaDataFormat:             "toml"
newContentEditor:           ""
# Don't sync modification time of files
noTimes:                    false
paginate:                   10
paginatePath:               "page"
permalinks:
  post: /:slug/:title/
# Pluralize titles in lists using inflect
pluralizeListTitles:        true
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames:      false
# filesystem path to write files to
publishdir:                 "docs"
# enables syntax guessing for code fences without specified language
pygmentsCodeFencesGuessSyntax: false
# color-codes for highlighting derived from this style
pygmentsStyle:              "monokai"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses:         false
# default sitemap configuration map
sitemap:
# filesystem path to read files relative from
source:                     ""
staticdir:                  "static"
# display memory and timing of different steps of the program
stepAnalysis:               false
# theme to use (located by default in /themes/THEMENAME/)
themesdir:                  "themes"
theme:                      "blackburn"
title:                      "code.openark.org"
# if true, use /filename.html instead of /filename/
uglyURLs:                   false
# Do not make the url/path to lowercase
disablePathToLower:         true
# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage:             false
# verbose output
verbose:                    false
# verbose logging
verboseLog:                 false
# watch filesystem for changes and recreate as needed
watch:                      true
# Special additions:
# pygmentsUseClasses:         true
# #disqusShortname: "XXX"
# #googleAnalytics: "XXX"
# params:
#   logo: "/images/shlomi-noach.png"
#   subtitle: "hola"
# author:
#   name: "Shlomi Noach"
#   github: "shlomi-noach"
#   twitter: "ShlomiNoach"
#   linkedin: "in/shlominoach"
#   stackoverflow: "1505860/shlomi-noach"
# taxonomies:
#   tag: "tags"
#   category: "categories"
#   series: "series"
# menu:
#   main:
#     - name: "Blog"
#       url: "/"
#       weight: 1
#     - name: "About"
#       url: "/page/about/"
#       weight: 2

baseurl: "blog/"
languageCode: "en-us"
title: "code.openark.org"
theme: "blackburn"
copyright: "&copy; 2016. All rights reserved."
canonifyurls: true
paginate: 10
# RSSlink: "/rss"

taxonomies:
  tag: "tag"
  category: "category"
  series: "series"

params:
  # Shown in the home page
  author: "Shlomi Noach"
  subtitle: "Software musings by Shlomi Noach"
  brand: "openark.org"
  googleAnalytics: "Your Google Analytics tracking ID"
  disqus: "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs: "androidstudio"
  dateFormat: "02 Jan 2006"
  logo: "/images/shlomi-noach.png"

menu:
  main:
  - name: "Home"
    pre: "<i class='fa fa-home fa-fw'></i>"
    weight: 0
    identifier: "home"
    url: "/"
  - name: "Posts"
    pre: "<i class='fa fa-list fa-fw'></i>"
    weight: 1
    identifier: "post"
    url: "/post/"
  - name: "About"
    pre: "<i class='fa fa-user fa-fw'></i>"
    weight: 2
    identifier: "about"
    url: "/page/about"

social:
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter: "ShlomiNoach"
  github: "shlomi-noach"
  stackoverflow: "" # "1505860/shlomi-noach"
  linkedin: "shlominoach"
---
